export const CHECK_EMAIL_DUPLICATE_REQUEST = "CHECK_EMAIL_DUPLICATE_REQUEST"; //이메일 중복검사 액션
export const CHECK_EMAIL_DUPLICATE_SUCCESS = "CHECK_EMAIL_DUPLICATE_SUCCESS";
export const CHECK_EMAIL_DUPLICATE_FAILURE = "CHECK_EMAIL_DUPLICATE_FAILURE";


export const CHECK_NICKNAME_DUPLICATE_REQUEST = "CHECK_NICKNAME_DUPLICATE_REQUEST"; //닉네임 중복검사 액션
export const CHECK_NICKNAME_DUPLICATE_SUCCESS = "CHECK_NICKNAME_DUPLICATE_SUCCESS";
export const CHECK_NICKNAME_DUPLICATE_FAILURE = "CHECK_NICKNAME_DUPLICATE_FAILURE";
